language: node_js
if: tag IS blank
notifications:
  email: false
node_js:
  - stable
cache: yarn
before_script:
  - yarn run build
script:
  - yarn run check
before_deploy:
  - source scripts/prepare_git_release.sh
deploy:
  # Make stable releases following the conventional commits specification
  # when commits are pushed to master
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: yarn run lerna publish --yes
  # Make canary releases tagged with git SHAs
  # when commits are pushed to other branches
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
    script:
      yarn run lerna publish --canary --preid "git-$TRAVIS_BRANCH" --dist-tag
      "git-$TRAVIS_BRANCH" --exact --yes
env:
  global:
    - secure: TWYDjBeK3L4rZfptfvf6YITUGEiLG+E7kvd4Siw1pDbbofnudgNr2EcFWtplxOQgd+yl6hLzgqLkCibpX7abc3p8yzi0NxedKKEnweqxfOSwjJ/bfzcVkXAdOe/w/hc1kHRO1BExU8ZO09xxCqMOZtZEgKeQjMuAKdh90D+HrKbrXL+fgBHMgGQrUvtf3MylL2zYfA/rmY5s42N1z8AFpNmYUy+H/LmPLapoSOENJRwe/6MTKgt3WEaX06loXnO6uRo/1t3uYjPaquJqfcdgqks/u/DvKJ9YINrsF/UDyWuVAniDCu/1rDjMJwMEXBQNKNuB4ZzDZt3cEcsjY5Xsa9Rsab8kR9LlH+Kvzm4WqPC+L8WZVL4qTc+L9EkIEN5fFo4fc4Nnsc2jY1JrT+fyoBTRrDon6xaWFqTaXGESX1mXytBA6saqOOBLnpzpw40rkdE6ySVtgYn0OiSAvTWTOuR8yyqOOg4M1TVQ8ZrYw/UmYCmlxA7FA82HJXk5m3DENpPU7KgLQy+6ncysc4OJjbj/D0CkrC36UY6uVx9xf+bIzS6Ctwjo0pIj3JBu6S68gNuQjr9RssA0o9W9DYiZxZCa+R+kLGW/jPo7DIKDE68EAa9SNOlcMg5KqoJgCaJPlAuvVWepUH/ZA2FwLlMXWlUgjSIRZpvZGtvJX/2ZoKo= # SNYK_TOKEN
    # - secure: kA9kOL6uTGjxAGTJNI98QfDgFH2QFUkO4Oi/KBAiJQ5npHfTzGrtJFcPdsq4RYkMS+zLHD+51Slu47MKO/oZMaVV7762OrvE4XJkg9CMGSW0GrSBF544GlGDsoYYSmgfceW6vseOWDuV862KctOKXD/y1l3UbwGBn2KwXAWGMnTIiSmVkQjvZlaMRM+KbT129/9Kd9r9D5YAUNBsLUbbtn7pjjmDfZCsQo3emVKBscv7EtjD/DhqNsG1aGKatf/ApgspUyKDO1xBM9K9gzuFD8dqXUsXHNAw7X7zcnjljgEX/IY4sttMjmGm4XgU4Zb11zRqc6EnamR0WNbziL8LHIc22S3l705yJE+Ov48oUJmuC3LoIsLLyLSBRnFuhtXQr+S8SLpXl6dICu3nSBtRcDILClMXRfsYkZgT3lLKxCSj1fZKDXSaij3hHQ2d2jPG3lId03d0Z6DRAyVAxfd4fIrG9umMzBsRiCB4JVBIbIRXfjfGAz1odWog2GKXdMnJRGRWT96V452T+ZLiXXCSkHT56e8tB0pl1G5FNcv+pm0kjkHktjMNq8DswGu71fekRZdPPJWRAPc2ipHMynfScvELsJWhGWEtRAGW0vxwncx3Nf8Grts1CIfe3U4tgWlQprlB+h8AmxncC7XVJqseSoOfu2fykMWYhT9nvpHO2lE= # NPM_TOKEN
