language: node_js
node_js:
  - stable
cache: yarn
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5156be73e058008e1ed2
    on_success: always
    on_failure: always
    on_start: never
before_script:
  - yarn run build
script:
  - yarn run check
before_deploy:
  - source scripts/prepare_git_release.sh
deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: yarn run lerna publish --yes
  - provider: script
    skip_cleanup: true
    on:
      branch: next
    script:
      yarn run lerna publish prerelease --preid alpha --dist-tag alpha --exact
      --no-conventional-commits --yes
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
    if: tag IS blank
    script:
      yarn run lerna publish --canary --dist-tag "git-$TRAVIS_BRANCH" --preid
      "git-$TRAVIS_BRANCH" --yes --force-publish --exact
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    - secure: TWYDjBeK3L4rZfptfvf6YITUGEiLG+E7kvd4Siw1pDbbofnudgNr2EcFWtplxOQgd+yl6hLzgqLkCibpX7abc3p8yzi0NxedKKEnweqxfOSwjJ/bfzcVkXAdOe/w/hc1kHRO1BExU8ZO09xxCqMOZtZEgKeQjMuAKdh90D+HrKbrXL+fgBHMgGQrUvtf3MylL2zYfA/rmY5s42N1z8AFpNmYUy+H/LmPLapoSOENJRwe/6MTKgt3WEaX06loXnO6uRo/1t3uYjPaquJqfcdgqks/u/DvKJ9YINrsF/UDyWuVAniDCu/1rDjMJwMEXBQNKNuB4ZzDZt3cEcsjY5Xsa9Rsab8kR9LlH+Kvzm4WqPC+L8WZVL4qTc+L9EkIEN5fFo4fc4Nnsc2jY1JrT+fyoBTRrDon6xaWFqTaXGESX1mXytBA6saqOOBLnpzpw40rkdE6ySVtgYn0OiSAvTWTOuR8yyqOOg4M1TVQ8ZrYw/UmYCmlxA7FA82HJXk5m3DENpPU7KgLQy+6ncysc4OJjbj/D0CkrC36UY6uVx9xf+bIzS6Ctwjo0pIj3JBu6S68gNuQjr9RssA0o9W9DYiZxZCa+R+kLGW/jPo7DIKDE68EAa9SNOlcMg5KqoJgCaJPlAuvVWepUH/ZA2FwLlMXWlUgjSIRZpvZGtvJX/2ZoKo= # SNYK_TOKEN
    - secure: YhChLkNSiUfpoABwJ4tKhehjl9UtorhFYjI+wc2mQlKEmh5lMxggRwG4shgTNALIhxM7N6xQFbjEeQC28UlkdDc1fxeTKwiDhH9hpqkdoI9y0weVLDNRLEp2ap+BH3mELwTF3iVg5+9bXJ/ZRNEBdpwW7z4vjaG8ZSfHrdnnjukvqriXMzhIo8Tv3uulyjDY9G3o6TTcRlq3yjpCz5/M6OvBjOxWSxv6ljE9IrD5gaKv7nKePLiBoc4OAcmpLiMhBNELOukemmWsPhbZUOcTvGDkfpeqhSBraEZguNQy/9zXVLGPV/qNUjsJcU/veB721z3zZI6af7xl2vC7Rjm16MkCS1dNJWVHqGls06ayo1sn0Z2VlWsLzeykfF2erlGKR5bAivCJpj2qVUx94SrjwHwpFaOMaf6Ca527nl2PyVg3gjGPbcp6AAKpFybTnasn0knBp2ZMW9w+24Rhd8dL7rdrlxnyJ5DD/6yn2dWJ6BIUuaACUAHq+73rxy/A2hnS2pP52eBgjTq2jTxtkx56pBU4yvNT7DJ5yuLyQDTZdxe2QGcihP+TybGJPuiEbIrvhG7QhZmx70QcnbcCUOQV2GH61TMfw1yvbbT5H/N6MLUAgpFxBG04D5VxZLwQTBwJNUxlxyIvSH3RkQ5PBCriR+NDml0wlJfobP3aRi+h0N4= # NPM_TOKEN
